// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vesta.Infrastructure.Persistence;

#nullable disable

namespace Vesta.Infrastructure.Migrations
{
    [DbContext(typeof(VestaDbContext))]
    [Migration("20260809200023_AddQuestionTypeAndQuestionOptions")]
    partial class AddQuestionTypeAndQuestionOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vesta.Domain.Entities.AnswerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_question_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_answers_user_id");

                    b.HasIndex("DailyQuestionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_answers_daily_question_id_user_id");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_question_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("DailyQuestionId")
                        .HasDatabaseName("ix_comments_daily_question_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.DailyQuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date")
                        .HasColumnName("assigned_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_questions");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_daily_questions_question_id");

                    b.HasIndex("FamilyId", "AssignedDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_questions_family_id_assigned_date");

                    b.ToTable("daily_questions", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.FamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_families_created_by");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.FamilyMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.InviteCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IntendedRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("intended_role");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_invite_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invite_codes_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invite_codes_created_by");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_invite_codes_family_id");

                    b.ToTable("invite_codes", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read")
                        .HasFilter("\"IsRead\" = false");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("MultipleChoice")
                        .HasColumnName("question_type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.QuestionOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOther")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_other");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId", "SortOrder")
                        .HasDatabaseName("ix_question_options_question_id_sort_order");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth0id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0Id")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Vesta.Domain.Entities.AnswerEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.DailyQuestionEntity", "DailyQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("DailyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_daily_questions_daily_question_id");

                    b.HasOne("Vesta.Domain.Entities.UserEntity", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_users_user_id");

                    b.Navigation("DailyQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.CommentEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.DailyQuestionEntity", "DailyQuestion")
                        .WithMany("Comments")
                        .HasForeignKey("DailyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_daily_questions_daily_question_id");

                    b.HasOne("Vesta.Domain.Entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("DailyQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.DailyQuestionEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.FamilyEntity", "Family")
                        .WithMany("DailyQuestions")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_questions_families_family_id");

                    b.HasOne("Vesta.Domain.Entities.QuestionEntity", "Question")
                        .WithMany("DailyQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_questions_questions_question_id");

                    b.Navigation("Family");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.FamilyEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_created_by");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.FamilyMemberEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.FamilyEntity", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("Vesta.Domain.Entities.UserEntity", "User")
                        .WithMany("FamilyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.InviteCodeEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invite_codes_users_created_by");

                    b.HasOne("Vesta.Domain.Entities.FamilyEntity", "Family")
                        .WithMany("InviteCodes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invite_codes_families_family_id");

                    b.Navigation("Creator");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.QuestionOptionEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.QuestionEntity", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("Vesta.Domain.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Vesta.Domain.Entities.UserEntity", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.DailyQuestionEntity", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.FamilyEntity", b =>
                {
                    b.Navigation("DailyQuestions");

                    b.Navigation("InviteCodes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.QuestionEntity", b =>
                {
                    b.Navigation("DailyQuestions");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Vesta.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");

                    b.Navigation("FamilyMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
